# Generated by Django 3.0 on 2020-02-02 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceManufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'DeviceManufacturer',
                'verbose_name_plural': 'DeviceManufacturer',
                'db_table': 'DeviceManufacturer',
            },
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'DeviceType',
                'verbose_name_plural': 'DeviceTypes',
                'db_table': 'DeviceType',
            },
        ),
        migrations.CreateModel(
            name='DeviceInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50)),
                ('service_tag', models.CharField(max_length=50)),
                ('express_service_code', models.CharField(max_length=50)),
                ('mac_address', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('number_of_rack_unit', models.PositiveSmallIntegerField()),
                ('device_model', models.CharField(default='', max_length=502)),
                ('device_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.DeviceType')),
                ('manufacturer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.DeviceManufacturer')),
            ],
            options={
                'verbose_name': 'DeviceInventory',
                'verbose_name_plural': 'DeviceInventory',
                'db_table': 'DeviceInventory',
            },
        ),
        migrations.CreateModel(
            name='DeviceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_detail', models.CharField(max_length=250)),
                ('device_manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.DeviceManufacturer')),
            ],
            options={
                'verbose_name': 'DeviceDetails',
                'verbose_name_plural': 'DeviceDetails',
                'db_table': 'DeviceDetail',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_rack_unit_position', models.PositiveSmallIntegerField()),
                ('ending_rack_unit_position', models.PositiveSmallIntegerField()),
                ('rack_id', models.PositiveIntegerField()),
                ('device_inventory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.DeviceInventory')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'db_table': 'Device',
            },
        ),
    ]
