# Generated by Django 3.0 on 2020-02-14 19:42

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceHostName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'DeviceHostName',
                'verbose_name_plural': 'DeviceHostName',
                'db_table': 'DeviceHostname',
            },
        ),
        migrations.CreateModel(
            name='DeviceManufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'DeviceManufacturer',
                'verbose_name_plural': 'DeviceManufacturer',
                'db_table': 'DeviceManufacturer',
            },
        ),
        migrations.CreateModel(
            name='DeviceRackLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'DeviceRackLocation',
                'verbose_name_plural': 'DeviceRackLocation',
                'db_table': 'DeviceRackLocation',
            },
        ),
        migrations.CreateModel(
            name='DeviceRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'DeviceRole',
                'verbose_name_plural': 'DeviceRole',
                'db_table': 'DeviceRole',
            },
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'DeviceType',
                'verbose_name_plural': 'DeviceTypes',
                'db_table': 'DeviceType',
            },
        ),
        migrations.CreateModel(
            name='PatchPort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'PatchPort',
                'verbose_name_plural': 'PatchPort',
                'db_table': 'PatchPort',
            },
        ),
        migrations.CreateModel(
            name='PortFunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'PortFunction',
                'verbose_name_plural': 'PortFunction',
                'db_table': 'PortFunction',
            },
        ),
        migrations.CreateModel(
            name='PortSpeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'PortSpeed',
                'verbose_name_plural': 'PortSpeed',
                'db_table': 'PortSpeed',
            },
        ),
        migrations.CreateModel(
            name='PortType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'PortType',
                'verbose_name_plural': 'PortTypes',
                'db_table': 'PortType',
            },
        ),
        migrations.CreateModel(
            name='SwitchPort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'SwitchPort',
                'verbose_name_plural': 'SwitchPort',
                'db_table': 'SwitchPort',
            },
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_role', models.ForeignKey(on_delete=django.db.models.fields.CharField, to='device.DeviceRole')),
                ('device_type', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='device.DeviceType')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.DeviceManufacturer')),
            ],
            options={
                'verbose_name': 'Switch',
                'verbose_name_plural': 'Switch',
                'db_table': 'Switch',
            },
        ),
        migrations.CreateModel(
            name='DeviceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_detail', models.CharField(max_length=250)),
                ('device_manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.DeviceManufacturer')),
            ],
            options={
                'verbose_name': 'DeviceDetails',
                'verbose_name_plural': 'DeviceDetails',
                'db_table': 'DeviceDetail',
            },
        ),
    ]
