# Generated by Django 3.0 on 2020-02-14 20:00

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='device_role',
            field=models.OneToOneField(on_delete=django.db.models.fields.CharField, to='device.DeviceRole'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='device_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='device.DeviceType'),
        ),
    ]
