# Generated by Django 3.0 on 2020-02-02 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deviceinventory',
            old_name='device_type_id',
            new_name='device_type',
        ),
        migrations.RenameField(
            model_name='deviceinventory',
            old_name='manufacturer_id',
            new_name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='deviceinventory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='deviceinventory',
            name='device_model',
        ),
        migrations.RemoveField(
            model_name='deviceinventory',
            name='express_service_code',
        ),
        migrations.RemoveField(
            model_name='deviceinventory',
            name='mac_address',
        ),
        migrations.RemoveField(
            model_name='deviceinventory',
            name='number_of_rack_unit',
        ),
        migrations.RemoveField(
            model_name='deviceinventory',
            name='serial_number',
        ),
        migrations.RemoveField(
            model_name='deviceinventory',
            name='service_tag',
        ),
        migrations.AddField(
            model_name='deviceinventory',
            name='device_detail',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='device.DeviceDetail'),
        ),
    ]
