# Generated by Django 3.0 on 2020-02-14 20:28

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_auto_20200214_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'DataCenter',
                'verbose_name_plural': 'DataCenter',
                'db_table': 'DataCenter',
            },
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Rack',
                'verbose_name_plural': 'Rack',
                'db_table': 'Rack',
            },
        ),
        migrations.AddField(
            model_name='switch',
            name='device_description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='device_hostname',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.fields.CharField, to='device.DeviceHostName'),
        ),
        migrations.AddField(
            model_name='switch',
            name='data_center',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.fields.CharField, to='device.DataCenter'),
        ),
        migrations.AddField(
            model_name='switch',
            name='rack',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.fields.CharField, to='device.Rack'),
        ),
    ]
