# Generated by Django 3.0 on 2020-02-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_auto_20200202_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortSpeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'PortSpeed',
                'verbose_name_plural': 'PortSpeed',
                'db_table': 'PortSpeed',
            },
        ),
        migrations.CreateModel(
            name='PortType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'PortType',
                'verbose_name_plural': 'PortTypes',
                'db_table': 'PortType',
            },
        ),
    ]
