# Generated by Django 3.0 on 2020-02-17 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_auto_20200217_0001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='switch',
            name='port',
        ),
        migrations.AddField(
            model_name='port',
            name='switch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='device.Switch'),
            preserve_default=False,
        ),
    ]
