# Generated by Django 3.0 on 2020-02-14 20:35

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_auto_20200214_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='device_role',
            field=models.OneToOneField(default=1, on_delete=django.db.models.fields.CharField, to='device.DeviceRole'),
        ),
    ]
