# Generated by Django 3.0 on 2020-02-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_portspeedtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portspeed',
            name='speed',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
