# Generated by Django 3.0 on 2020-02-17 18:27

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_auto_20200217_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='rack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.fields.CharField, to='device.Rack'),
        ),
    ]
