# Generated by Django 3.0 on 2020-02-14 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_auto_20200214_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwitchLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'SwitchLabel',
                'verbose_name_plural': 'SwitchLabel',
                'db_table': 'SwitchLabel',
            },
        ),
        migrations.AddField(
            model_name='switch',
            name='patch_port',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='device.PatchPort'),
        ),
        migrations.AddField(
            model_name='switch',
            name='switch_label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='device.SwitchLabel'),
        ),
    ]
