# Generated by Django 3.0 on 2020-02-06 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0005_auto_20200206_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortFunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'PortFunction',
                'verbose_name_plural': 'PortFunction',
                'db_table': 'PortFunction',
            },
        ),
    ]
