# Generated by Django 3.0 on 2020-03-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0005_auto_20200217_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
