# Generated by Django 3.0 on 2020-02-14 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0005_auto_20200214_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='switchport',
            name='number',
        ),
        migrations.AddField(
            model_name='switch',
            name='switch_port',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='device.SwitchPort'),
        ),
        migrations.AddField(
            model_name='switchport',
            name='port',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
