# Generated by Django 3.0 on 2020-02-12 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0006_portfunction'),
    ]

    operations = [
        migrations.CreateModel(
            name='VLan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'VLan',
                'verbose_name_plural': 'VLans',
                'db_table': 'VLan',
            },
        ),
    ]
