# Generated by Django 3.0 on 2020-02-12 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0007_vlan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vlan',
            old_name='name',
            new_name='description',
        ),
        migrations.AddField(
            model_name='vlan',
            name='number',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
