# Generated by Django 3.0 on 2020-03-01 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0007_auto_20200301_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='port',
            old_name='switch_id',
            new_name='switch',
        ),
    ]
