# Generated by Django 3.0 on 2020-02-12 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0008_auto_20200212_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevicePurpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'DevicePurpose',
                'verbose_name_plural': 'DevicePurpose',
                'db_table': 'DevicePurpose',
            },
        ),
        migrations.DeleteModel(
            name='VLan',
        ),
    ]
