# Generated by Django 3.0 on 2020-02-12 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0009_auto_20200212_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceRackLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'DeviceRackLocation',
                'verbose_name_plural': 'DeviceRackLocation',
                'db_table': 'DeviceRackLocation',
            },
        ),
        migrations.DeleteModel(
            name='PortSpeedType',
        ),
    ]
