# Generated by Django 3.0 on 2020-02-12 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0010_auto_20200212_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatchPort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'PatchPort',
                'verbose_name_plural': 'PatchPort',
                'db_table': 'PatchPort',
            },
        ),
        migrations.CreateModel(
            name='SwitchPort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'SwitchPort',
                'verbose_name_plural': 'SwitchPort',
                'db_table': 'SwitchPort',
            },
        ),
    ]
